name: main
on:
  push:
    branches:
      - main
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Execute dangerous input
        run: echo ${{ github.event.head_commit.message }}
