name: main
on:
  push:
    branches:
      - main
jobs:
  main:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        run: echo ${{ secrets.SOME_SECRET }}
