name: main
on:
  pull_request:
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Hello world
        run: echo hello world

      - name: Hijacked run
        run: echo hehehe
