name: Private
on:
  push:
    # This runs on fork branches too
    branches: ["*"]
jobs:
  private:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.COMMIT_TOKEN }}
          ref: ${{ github.ref }}
